[package]
name = "holochain_persistence_api"
version = "0.0.18"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
build = "build.rs"
description = "persistence api for content addressable storage and entity attribute value indexes"
keywords = ["holochain", "holo", "persistence", "cas", "eav"]
categories = ["database"]
license = "Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/holochain_persistence_api"
repository = "https://github.com/holochain/holochain-persistence"

[dependencies]
arrayref = "=0.3.5"
base64 = "=0.10.1"
chrono = "=0.4.6"
serde = "=1.0.104"
lazy_static = "=1.4.0"
regex = "=1.1.2"
serde_derive = "=1.0.104"
serde_json = { version = "=1.0.47", features = ["preserve_order"] }
multihash = "=0.8.0"
futures = "=0.3.1"
hcid = "=0.0.6"
shrinkwraprs = "=0.2.1"
rust-base58 = "=0.0.4"
objekt= "=0.1.2"
holochain_json_api = "=0.0.23"
holochain_json_derive = "=0.0.23"
uuid = { version = "=0.7.1", features = ["v4"] }
rand = "=0.7.3"

[dev-dependencies]
maplit = "=1.0.1"
